Make everything intuitiv
+ Rename deps -> pkg
+ Rename repo -> catalog
+ Rename plugin -> parser
+ Seperate backend/repo into backend/catalog
+ Make API in epm_{pkg,catalog} consistent
+ Add pluggable backend for epm_catalog
+ Always pass configuration to ensure correct app state
+ Make common log fun in epm:log
+ Move os & cache specific fun's in own modules
+ Add API docs
+ Add support for k/v options in epm config
+ Add --rebar option to work directly with rebar
+ Clearer responsibility for epm_pkg vs epm_agent_*
+ Add general logging throught epm:log/3
+ Seperate cache related code into own module
+ Remove epm_utils.erl, epm.hrl
+ Add epm_os:* for OS interaction (Adds error code to old epm_utils:cmd call)
+ Add lenses to fetch a specific dependency graph
+ Add config callbacks
+ Add 2nd callback for epm:unless/2 and epm:ifthen/2
+ Add support for traversing config and lists of catalogs
+ Move git related functions into their own module -> epm_git
+ Make git agent work with packages instead of paths
+ Add epm_pkg:flatten/1 for getting all dependencies

diff --git a/bin/epmpp b/bin/epmpp
--- a/bin/epmpp
+++ b/bin/epmpp
@@ -1,17 +1,17 @@
 #/bin/bash
 
-basedir=${1:-"."}
-conffile=${basedir}/epm.config
+conffile=${1:-"."}
+[ -f "$conffile" ] || conffile="${conffile}/epm.config"
 tmpfile=.cfg-parser
-
-if [ ! -r "${conffile}" ]; then
-	echo "error: ${conffile} not found."
-	exit 1
-fi
 
 err() {
 	echo $1 >&2
 }
+
+if [ ! -r "${conffile}" ]; then
+	err "error: ${conffile} not found, not readable"
+	exit 1
+fi
 
 grep -nP '^[a-z\t]' $conffile > $tmpfile
 targets=$(grep -P '[0-9]+:[a-z].*' $tmpfile | sed -E 's/\s+//g')
@@ -24,7 +24,15 @@ for target in $targets; do
 	fi
 done
 
-sed -E 's/[0-9]+://;s/([^^])\s+/\1/g;s/^\s/ /' $tmpfile
-rm $tmpfile
+sed -nE '
+s/^[^a-z \t].*//;/^$/d;   # remove non-parsable lines
+/\[/ { :r;                # Start loop looking for end ]
+	/\]/!N;
+	s/,?\n/,/;s/\[,/[/;   # Concatenate lines and fix commas
+	tr};                  # If ending ] is not found, repeat
+s/(.)\s+/\1/g; s/^\s+/ /; # Normalize spaces
+p' $conffile
+
+rm $tmpfile 2> /dev/null
 
 exit 0
